apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechanic
  labels:
    app: mechanic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mechanic
  template:
    metadata:
      labels:
        app: mechanic
    spec:
      containers:
        - name: mechanic
          image: "879772956301.dkr.ecr.ap-southeast-2.amazonaws.com/user04/mechanic:v1"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
      imagePullSecrets:
        - name: ecr-secret