---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt
  labels:
    app: receipt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt
  template:
    metadata:
      labels:
        app: receipt
    spec:
      containers:
        - name: receipt
          image: username/receipt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  labels:
    app: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: username/shop:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicleparts
  labels:
    app: vehicleparts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicleparts
  template:
    metadata:
      labels:
        app: vehicleparts
    spec:
      containers:
        - name: vehicleparts
          image: username/vehicleparts:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: username/dashboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mechanic
  labels:
    app: mechanic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mechanic
  template:
    metadata:
      labels:
        app: mechanic
    spec:
      containers:
        - name: mechanic
          image: username/mechanic:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: receipt
  labels:
    app: receipt
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: receipt


---


apiVersion: v1
kind: Service
metadata:
  name: shop
  labels:
    app: shop
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: shop


---


apiVersion: v1
kind: Service
metadata:
  name: vehicleparts
  labels:
    app: vehicleparts
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: vehicleparts


---


apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dashboard


---


apiVersion: v1
kind: Service
metadata:
  name: mechanic
  labels:
    app: mechanic
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mechanic

