apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicleparts
  labels:
    app: vehicleparts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicleparts
  template:
    metadata:
      labels:
        app: vehicleparts
    spec:
      containers:
        - name: vehicleparts
          image: "879772956301.dkr.ecr.ap-southeast-2.amazonaws.com/user04/vehicleparts:v1"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
